// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID          int64
	Name        string
	Description pgtype.Text
	Cents       int64
	UserID      pgtype.Int8
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Permission struct {
	ID   int64
	Name string
}

type Role struct {
	ID          int64
	Name        string
	Description pgtype.Text
}

type RolesPermission struct {
	RoleID       int64
	PermissionID int64
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type UsersRole struct {
	UserID   int64
	RoleID   int64
	IsActive bool
}
