// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
  name,
  description,
  cents,
  user_id
) VALUES ( $1, $2, $3, $4 )
RETURNING id, name, description, cents, user_id, created_at, updated_at, deleted_at
`

type CreateExpenseParams struct {
	Name        string
	Description pgtype.Text
	Cents       int64
	UserID      pgtype.Int8
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Name,
		arg.Description,
		arg.Cents,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Cents,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name,
  email,
  password
) VALUES ( $1, $2, $3 )
RETURNING id, name, email, password, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpenseById = `-- name: DeleteExpenseById :exec
UPDATE expenses
  SET deleted_at = NOW()
  WHERE id = $1
`

func (q *Queries) DeleteExpenseById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteExpenseById, id)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
UPDATE users
  SET deleted_at = NOW()
  WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserByEmail, email)
	return err
}

const deleteUserById = `-- name: DeleteUserById :exec
UPDATE users
  SET deleted_at = NOW()
  WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUserById, id)
	return err
}

const getExpenseById = `-- name: GetExpenseById :one

SELECT id, name, description, cents, user_id, created_at, updated_at, deleted_at 
FROM expenses 
WHERE id = $1 
LIMIT 1
`

// - EXPENSES ---
func (q *Queries) GetExpenseById(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseById, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Cents,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenses = `-- name: GetExpenses :many
SELECT id, name, description, cents, user_id, created_at, updated_at, deleted_at 
FROM expenses 
ORDER BY id
LIMIT $1 
OFFSET $2
`

type GetExpensesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetExpenses(ctx context.Context, arg GetExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getExpenses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Cents,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByUserEmail = `-- name: GetExpensesByUserEmail :many
SELECT 
  expenses.id AS expense_id, 
  expenses.name AS expense_name, 
  expenses.cents, 
  users.id AS user_id, 
  users.name AS user_name, 
  users.email AS user_email
FROM expenses
  LEFT JOIN users
  ON users.id = expenses.user_id
WHERE users.email = $1
AND users.deleted_at IS NULL
`

type GetExpensesByUserEmailRow struct {
	ExpenseID   int64
	ExpenseName string
	Cents       int64
	UserID      pgtype.Int8
	UserName    pgtype.Text
	UserEmail   pgtype.Text
}

func (q *Queries) GetExpensesByUserEmail(ctx context.Context, email string) ([]GetExpensesByUserEmailRow, error) {
	rows, err := q.db.Query(ctx, getExpensesByUserEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpensesByUserEmailRow
	for rows.Next() {
		var i GetExpensesByUserEmailRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.ExpenseName,
			&i.Cents,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByUserId = `-- name: GetExpensesByUserId :many
SELECT 
  expenses.id AS expense_id, 
  expenses.name AS expense_name, 
  expenses.cents, 
  users.id AS user_id, 
  users.name AS user_name, 
  users.email AS user_email
FROM expenses
  LEFT JOIN users
  ON users.id = expenses.user_id
WHERE expenses.user_id = $1
AND users.deleted_at IS NULL
`

type GetExpensesByUserIdRow struct {
	ExpenseID   int64
	ExpenseName string
	Cents       int64
	UserID      pgtype.Int8
	UserName    pgtype.Text
	UserEmail   pgtype.Text
}

func (q *Queries) GetExpensesByUserId(ctx context.Context, userID pgtype.Int8) ([]GetExpensesByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getExpensesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpensesByUserIdRow
	for rows.Next() {
		var i GetExpensesByUserIdRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.ExpenseName,
			&i.Cents,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, 
  name, 
  email, 
  created_at, 
  updated_at, 
  deleted_at 
FROM users 
WHERE email = $1 
AND deleted_at IS NULL
LIMIT 1
`

type GetUserByEmailRow struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one


SELECT 
  id, 
  name, 
  email, 
  created_at, 
  updated_at, 
  deleted_at 
FROM users 
WHERE id = $1
AND deleted_at IS NULL
LIMIT 1
`

type GetUserByIdRow struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Queries for Expense Tracker
// - USERS ---
func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, 
  name, 
  email, 
  created_at, 
  updated_at, 
  deleted_at 
FROM users 
WHERE deleted_at IS NULL
ORDER BY id
LIMIT $1 
OFFSET $2
`

type GetUsersParams struct {
	Limit  int32
	Offset int32
}

type GetUsersRow struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT 
  users.id AS user_id, 
  users.name AS user_name, 
  users.email AS user_email, 
  roles.id AS role_id, 
  roles.name AS role_name
  FROM users
  JOIN users_roles
  ON users.id = users_roles.user_id
  JOIN roles 
  ON roles.id = users_roles.role_id
  WHERE roles.id = $1 
  AND users_roles.is_active = true 
  AND users.deleted_at IS NULL
  ORDER BY roles.name DESC
`

type GetUsersByRoleRow struct {
	UserID    int64
	UserName  string
	UserEmail string
	RoleID    int64
	RoleName  string
}

func (q *Queries) GetUsersByRole(ctx context.Context, id int64) ([]GetUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByRoleRow
	for rows.Next() {
		var i GetUsersByRoleRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseById = `-- name: UpdateExpenseById :one
UPDATE expenses
  SET name = $2, description = $3, cents = $4 
  WHERE id = $1
RETURNING id, name, description, cents, user_id, created_at, updated_at, deleted_at
`

type UpdateExpenseByIdParams struct {
	ID          int64
	Name        string
	Description pgtype.Text
	Cents       int64
}

func (q *Queries) UpdateExpenseById(ctx context.Context, arg UpdateExpenseByIdParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpenseById,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Cents,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Cents,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserById = `-- name: UpdateUserById :one
UPDATE users
  SET name = $2, email = $3, password = $4
  WHERE id = $1
RETURNING id, name, email, password, created_at, updated_at, deleted_at
`

type UpdateUserByIdParams struct {
	ID       int64
	Name     string
	Email    string
	Password string
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserById,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
